// Generated by CoffeeScript 1.6.3
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  this.App = (function(_super) {
    __extends(App, _super);

    function App() {
      this.resize = __bind(this.resize, this);
      this.update = __bind(this.update, this);
      _ref = App.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    App.prototype.initialize = function() {
      return this.setup();
    };

    App.prototype.setup = function() {
      var canvas;
      canvas = document.getElementById('targetCanvas');
      paper.setup(canvas);
      this.waveOps = new WaveOps();
      paper.view.on('frame', this.update);
      return paper.view.on('resize', this.resize);
    };

    App.prototype.update = function() {
      if (this.get('paused') === true) {
        return;
      }
      this.trigger('update');
      return this.draw();
    };

    App.prototype.draw = function() {};

    App.prototype.resize = function(e) {
      return console.log(e);
    };

    return App;

  })(Backbone.Model);

}).call(this);
